#!/usr/bin/env python3
"""
ROP Demo Video Capture System

Captures demo videos using Playwright's built-in video recording.
Videos are used in presentations, documentation, and marketing.

Usage:
    python video_capture.py                    # Capture all videos
    python video_capture.py --video highlight  # Capture specific video
    python video_capture.py --list             # List available videos
    python video_capture.py --lang en          # Capture only English
"""

import argparse
import asyncio
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

try:
    from PIL import Image
except ImportError:
    Image = None

# Paths
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent
MANIFEST_FILE = SCRIPT_DIR / "video_manifest.yaml"


@dataclass
class VideoResult:
    """Result of a video capture."""

    video_id: str
    language: str
    success: bool
    output_path: Optional[Path] = None
    poster_path: Optional[Path] = None
    error: Optional[str] = None


def load_manifest() -> Dict[str, Any]:
    """Load the video manifest."""
    if not MANIFEST_FILE.exists():
        raise FileNotFoundError(f"Video manifest not found: {MANIFEST_FILE}")

    with open(MANIFEST_FILE, "r") as f:
        return yaml.safe_load(f)


async def capture_video(
    video_id: str,
    video_config: Dict[str, Any],
    manifest: Dict[str, Any],
    language: str = "en",
    force: bool = False,
) -> VideoResult:
    """Capture a single demo video using Playwright."""
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        return VideoResult(
            video_id=video_id,
            language=language,
            success=False,
            error="Playwright not installed. Run: pip install playwright && playwright install chromium",
        )

    # Construct output paths
    output_base = Path(manifest.get("output_base", "docs/deliverables/assets/videos"))
    output_dir = PROJECT_ROOT / output_base / language
    output_dir.mkdir(parents=True, exist_ok=True)

    video_output = output_dir / video_config["output"]

    # Skip if exists and not forcing
    if video_output.exists() and not force:
        print(f"  ⊙ Already exists: {video_output}")
        return VideoResult(
            video_id=video_id, language=language, success=True, output_path=video_output
        )

    try:
        async with async_playwright() as p:
            # Launch browser with video recording
            browser = await p.chromium.launch(headless=True)

            # Get video settings
            video_settings = manifest.get("video_settings", {})
            resolution = video_settings.get("resolution", {"width": 1920, "height": 1080})

            # Create context with video recording
            context = await browser.new_context(
                viewport=resolution,
                record_video_dir=str(output_dir / "temp"),
                record_video_size=resolution,
            )

            page = await context.new_page()

            # Construct demo URL
            base_url = manifest.get("base_url", f"file://{PROJECT_ROOT}/docs/deliverables/demo")
            url = f"{base_url}/{language}/index.html?mode=record"

            # Add chapter parameter if specified
            if video_config.get("chapter"):
                url += f"&chapter={video_config['chapter']}"

            print(f"  → Loading: {url}")
            await page.goto(url, wait_until="networkidle")

            # Wait for demo to complete
            duration = video_config.get("duration", 180000)
            print(f"  → Recording for {duration / 1000:.1f}s...")
            await page.wait_for_timeout(duration)

            # Close page and context to finalize video
            await page.close()
            await context.close()
            await browser.close()

            # Move video from temp to final location
            # Playwright creates video with a generated name
            temp_dir = output_dir / "temp"
            video_files = list(temp_dir.glob("*.webm"))

            if not video_files:
                return VideoResult(
                    video_id=video_id,
                    language=language,
                    success=False,
                    error="No video file generated by Playwright",
                )

            temp_video = video_files[0]

            # Convert WebM to MP4 using ffmpeg if available
            try:
                import subprocess

                # Check if ffmpeg is installed
                subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)

                # Convert to MP4 - High quality 1080p60
                subprocess.run(
                    [
                        "ffmpeg",
                        "-i",
                        str(temp_video),
                        "-c:v",
                        "libx264",
                        "-preset",
                        "slow",
                        "-crf",
                        "18",
                        "-profile:v",
                        "high",
                        "-level",
                        "4.2",
                        "-r",
                        "60",
                        "-pix_fmt",
                        "yuv420p",
                        "-movflags",
                        "+faststart",
                        "-y",
                        str(video_output),
                    ],
                    check=True,
                    capture_output=True,
                )

                print(f"  ✓ Converted to MP4: {video_output}")

            except (ImportError, subprocess.CalledProcessError, FileNotFoundError):
                # Fallback: Just move the WebM file
                print("  ⚠ ffmpeg not available, keeping WebM format")
                webm_output = video_output.with_suffix(".webm")
                shutil.move(str(temp_video), str(webm_output))
                video_output = webm_output

            # Clean up temp directory
            shutil.rmtree(temp_dir, ignore_errors=True)

            # Generate poster image if requested
            poster_path = None
            if manifest.get("build", {}).get("generate_posters", True):
                poster_path = await generate_poster(video_output, output_dir, video_id)

            return VideoResult(
                video_id=video_id,
                language=language,
                success=True,
                output_path=video_output,
                poster_path=poster_path,
            )

    except Exception as e:
        import traceback

        return VideoResult(
            video_id=video_id,
            language=language,
            success=False,
            error=f"{str(e)}\n{traceback.format_exc()}",
        )


async def generate_poster(video_path: Path, output_dir: Path, video_id: str) -> Optional[Path]:
    """Generate a poster image from the first frame of the video."""
    try:
        import subprocess

        poster_path = output_dir / f"{video_id}-poster.jpg"

        # Extract frame at 1 second using ffmpeg
        subprocess.run(
            [
                "ffmpeg",
                "-i",
                str(video_path),
                "-ss",
                "00:00:01.000",  # 1 second in
                "-vframes",
                "1",
                "-q:v",
                "2",  # High quality
                "-y",
                str(poster_path),
            ],
            check=True,
            capture_output=True,
        )

        print(f"  ✓ Generated poster: {poster_path}")
        return poster_path

    except Exception as e:
        print(f"  ⚠ Failed to generate poster: {e}")
        return None


async def capture_all_videos(
    video_ids: Optional[List[str]] = None,
    languages: Optional[List[str]] = None,
    force: bool = False,
) -> List[VideoResult]:
    """Capture multiple videos, optionally in parallel."""
    manifest = load_manifest()

    # Get configuration
    all_videos = manifest.get("videos", {})
    default_languages = manifest.get("languages", ["en"])
    languages = languages or default_languages

    # Filter videos if specific ones requested
    if video_ids:
        all_videos = {k: v for k, v in all_videos.items() if k in video_ids}

    # Sort by priority (high first)
    priority_order = {"high": 0, "medium": 1, "low": 2}
    sorted_videos = sorted(
        all_videos.items(), key=lambda x: priority_order.get(x[1].get("priority", "medium"), 1)
    )

    results = []
    max_concurrent = manifest.get("build", {}).get("max_concurrent", 2)

    # Create tasks for all language/video combinations
    tasks = []
    for video_id, video_config in sorted_videos:
        for language in languages:
            tasks.append((video_id, video_config, language))

    # Process in batches for controlled concurrency
    for i in range(0, len(tasks), max_concurrent):
        batch = tasks[i : i + max_concurrent]

        print(f"\n=== Processing batch {i // max_concurrent + 1} ===")

        # Run batch in parallel
        batch_results = await asyncio.gather(
            *[
                capture_video(video_id, config, manifest, lang, force)
                for video_id, config, lang in batch
            ]
        )

        results.extend(batch_results)

        # Report batch results
        for result in batch_results:
            if result.success:
                print(f"✓ {result.language.upper()}/{result.video_id}: {result.output_path}")
            else:
                print(f"✗ {result.language.upper()}/{result.video_id}: {result.error}")

    return results


def list_videos():
    """List all available videos from manifest."""
    manifest = load_manifest()

    print("\nAvailable Demo Videos:")
    print("=" * 70)

    for video_id, config in manifest.get("videos", {}).items():
        print(f"\n  {video_id}")
        print(f"    Description: {config.get('description', 'N/A')}")
        print(f"    Duration: {config.get('duration', 0) / 1000:.1f}s")
        print(f"    Output: {config.get('output', 'N/A')}")
        print(f"    Priority: {config.get('priority', 'medium')}")
        if config.get("chapter"):
            print(f"    Chapter: {config['chapter']}")
        if config.get("use_in"):
            print(f"    Use in: {', '.join(config['use_in'][:2])}")


def main():
    parser = argparse.ArgumentParser(description="Capture demo videos from ROP demos")
    parser.add_argument("--video", "-v", action="append", help="Specific video(s) to capture")
    parser.add_argument(
        "--lang", action="append", help="Specific language(s) to capture (e.g., en, no)"
    )
    parser.add_argument("--list", "-l", action="store_true", help="List available videos")
    parser.add_argument(
        "--force", "-f", action="store_true", help="Force regeneration even if files exist"
    )

    args = parser.parse_args()

    if args.list:
        list_videos()
        return

    # Capture videos
    print("\n" + "=" * 70)
    print("ROP Demo Video Capture")
    print("=" * 70)

    results = asyncio.run(capture_all_videos(args.video, args.lang, args.force))

    # Summary
    print(f"\n{'=' * 70}")
    success = sum(1 for r in results if r.success)
    failed = sum(1 for r in results if not r.success)

    print(f"Videos captured: {success}")
    if failed:
        print(f"Failed: {failed}")
        print("\nFailed videos:")
        for r in results:
            if not r.success:
                print(f"  - {r.language}/{r.video_id}: {r.error[:100]}...")

    # Check for required tools
    print(f"\n{'=' * 70}")
    print("System check:")

    try:
        import subprocess

        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
        print("  ✓ ffmpeg installed (MP4 conversion available)")
    except:
        print("  ⚠ ffmpeg not installed (videos will be in WebM format)")
        print("    Install: brew install ffmpeg  # macOS")
        print("             apt install ffmpeg   # Ubuntu")

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
